#!/usr/bin/env bash
# Generate llms-full.txt from llms.txt + public headers + docs.
# Usage: ./scripts/generate-llms.sh
# CI verifies the checked-in file is fresh (see .github/workflows/ci.yml).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
OUT="${REPO_ROOT}/llms-full.txt"

{
    echo "# zff llms-full.txt — generated by scripts/generate-llms.sh, do not edit"
    echo "# Source: llms.txt + include/zff public headers + top-level docs"
    echo
    cat "${REPO_ROOT}/llms.txt"
    for doc in README.md ARCHITECTURE.md ELEMENTS.md ROADMAP.md; do
        if [[ -f "${REPO_ROOT}/${doc}" ]]; then
            echo
            echo "======================================================================"
            echo "# File: ${doc}"
            echo "======================================================================"
            cat "${REPO_ROOT}/${doc}"
        fi
    done
    echo
    echo "======================================================================"
    echo "# File: CMakeLists.txt"
    echo "======================================================================"
    cat "${REPO_ROOT}/CMakeLists.txt"
    echo
    echo "======================================================================"
    echo "# Public headers: include/zff"
    echo "======================================================================"
    cd "${REPO_ROOT}"
    find include -name "*.h" | LC_ALL=C sort | while read -r h; do
        echo
        echo "--- File: ${h} ---"
        cat "${h}"
    done
} > "${OUT}"

echo "Wrote ${OUT} ($(wc -c < "${OUT}") bytes)"
